### ISSUE TITLE
CSS interferindo no estilo geral do site

### ISSUE THREAD

**Issue by alexlana** [tainacan/tainacan-wiki#2]
Olá! A versão 0.16 está interferindo no CSS global. Por exemplo, os links do site ficaram com a cor verde do Tainacan e os espaçamentos dos menus mudaram.

**Comment by mateuswetah** [comment]
Oi @alexlana tudo bem? Bora discutir isso daí, mas acho melhor no repositório do plugin (https://github.com/tainacan/tainacan), este aqui é o da wiki :)

Abre uma issue lá e de preferência já manda pra gente uma captura de tela pra gente dar uma olhada, pode ser?

**Comment by alexlana** [comment]
Foi mal! Eu não achei o repositório rápido e mandei errado :D
